title: Ben-Gurion University, Department of Computer Science <p> Formal Methods Seminar
description: This is the page of the weekly seminar on formal methods at the department of computer science of the Ben Gurion university of the Negev.
